language: julia

#os:
#  - osx

julia:
  - release

before_install:
  # Install LinuxBrew
  - unset DYLD_LIBRARY_PATH
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - echo -ne '\n' | ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"

install:
  - brew update
  - brew install pkg-config
  - brew doctor
  # Install MUMPS
  - brew tap homebrew/science
  - bash $TRAVIS_BUILD_DIR/travis.sh  # To keep logs small and periodic output.

# Then run default Julia script.

