language: julia

#os:
#  - osx

julia:
  - release

before_install:
  # Install LinuxBrew.
  - sudo apt-get update
  - sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
  - unset DYLD_LIBRARY_PATH
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - echo -ne '\n' | ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"
  # Ensure BLAS and LAPACK are available.
  - sudo apt-get -y install libblas-dev liblapack-dev

install:
  - brew update
  - brew install pkg-config
  # Install MUMPS.
  - brew tap homebrew/science
  #- bash $TRAVIS_BUILD_DIR/travis.sh  # To keep logs small and periodic output.
  - brew install cmake --env=std
  - brew install $(brew deps gcc)
  - travis_wait brew install gcc       # Can stay silent for longer than 10 mins.
  #- brew install $(brew deps scalapack)
  - brew install scalapack          # Request verbose output.
  - brew install mumps
  - export LD_LIBRARY_PATH=$(julia -E 'Pkg.dir()' | sed -e 's/"//g')/MUMPS/src:$LD_LIBRARY_PATH

# Then run default Julia script.

