language: objective-c

before_install:
  - brew update
  - brew tap staticfloat/julia
  - brew install julia

install:
  - brew tap homebrew/science
  - brew install mumps
  - export JULIA_PKG_DIR=$(julia -E 'Pkg.dir()' | sed -e 's/"//g')
  #- mkdir -vp $JULIA_PKG_DIR
  #- ln -s $TRAVIS_BUILD_DIR $JULIA_PKG_DIR/MUMPS
  - export LD_LIBRARY_PATH=$JULIA_PKG_DIR/MUMPS/src:$LD_LIBRARY_PATH
  - julia -E 'Pkg.clone(pwd())';
  - julia -E 'Pkg.build("MUMPS");'

script:
  - julia --check-bounds=yes -E 'Pkg.test("MUMPS")'

