language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
      julia: 1.0
      julia: nightly

branches:
  only:
    - master

before_install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` == "Linux" ]; then
      sudo apt-get install -y cmake git gfortran;
      wget --no-check-certificate https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz;
      tar -zxf openmpi-3.0.0.tar.gz;
      cd openmpi-3.0.0;
      sh ./configure --prefix=$HOME/OpenMPI > /dev/null;
      make -j > /dev/null;
      sudo make install > /dev/null;
    fi
  - if [ `uname` == "Darwin" ]; then
      brew --config; brew update; brew cask uninstall oclint; brew tap dpo/openblas; brew install mumps; fi
  - if [ `uname` == "Darwin" ]; then export TMPDIR=/tmp; fi  # for OpenMPI
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - julia -e 'versioninfo()'
  - julia -E 'Pkg.clone(pwd());'
  - julia -E 'Pkg.build("MUMPS");'
  - julia -E 'using BinDeps; BinDeps.debug("MUMPS")'

script:
  - julia --check-bounds=yes -E 'Pkg.test("MUMPS"; coverage=true)'
  - mpirun -np 2 julia $TRAVIS_BUILD_DIR/examples/mumps_mpi.jl

after_success:
  - julia -e 'cd(Pkg.dir("MUMPS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
