language: julia

os:
  - linux
  - osx

julia:
  - 0.6

branches:
  only:
    - master

before_install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` == "Linux" ]; then sudo apt-get install -y cmake git gfortran libopenmpi-dev openmpi-bin; fi
  - if [ `uname` == "Darwin" ]; then
      sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4";
      brew --config;
      brew update;
      brew cask uninstall oclint;
      brew tap dpo/openblas;
      brew install mumps;
    fi
  - if [ `uname` == "Darwin" ]; then export TMPDIR=/tmp; fi  # for OpenMPI
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - julia -e 'versioninfo()'
  - julia -E 'Pkg.clone(pwd());'
  - julia -E 'Pkg.build("MUMPS");'
  - julia -E 'using BinDeps; BinDeps.debug("MUMPS")'

script:
  - julia --check-bounds=yes -E 'Pkg.test("MUMPS"; coverage=true)'
  - mpirun julia $TRAVIS_BUILD_DIR/examples/mumps_mpi.jl

after_success:
  - julia -e 'cd(Pkg.dir("MUMPS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
