language: julia
#os:
#  - osx
julia:
  - release
before_install:
  # Install LinuxBrew
  #   Warning: Setting DYLD_* vars can break dynamic linking.
  - unset DYLD_LIBRARY_PATH
  #   Warning: You have a non-Homebrew 'pkg-config' in your PATH
  - sudo rm -f /usr/bin/pkg-config
  #   Warning: "config" scripts exist outside your system or Homebrew directories.
  - sudo rm -f /usr/local/clang-3.4/bin/llvm-config
  - cd ..
  - git clone https://github.com/Homebrew/linuxbrew.git
  - PATH=$PWD/linuxbrew/bin:$PATH
  - brew update
  # Install MUMPS
  - brew tap homebrew/science
  - brew install mumps

