language: julia

os:
  - osx
  - linux

julia:
  - release

before_install:
  # Install Linuxbrew.
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` = "Linux" ]; then bash setup_travis_linux.sh; fi
  - if [ `uname` = "Linux" ]; then export PATH="$HOME/.linuxbrew/bin:$PATH"; fi
  - brew --config
  - brew update
  - if [ `uname` = "Linux" ]; then brew install pkg-config; fi

install:
  # Install MUMPS.
  - brew tap homebrew/science
  - brew install cmake --without-docs  # On Linux, must happen before openssl.
  - if [ `uname` = "Linux" ]; then brew install scalapack; brew gist-logs scalapack; fi
  - brew install mumps
  - export JULIA_PKG_DIR=$(julia -E 'Pkg.dir()' | sed -e 's/"//g')
  - export LD_LIBRARY_PATH=$JULIA_PKG_DIR/MUMPS/src:$LD_LIBRARY_PATH
  - julia -E 'Pkg.clone(pwd())';
  - julia -E 'Pkg.build("MUMPS");'

script:
  - julia --check-bounds=yes -E 'Pkg.test("MUMPS")'
  - mpirun -np 2 julia $TRAVIS_BUILD_DIR/examples/mumps_mpi.jl

