language: julia
#os:
#  - osx
julia:
  - release
before_install:
  - cd ..
  - git clone https://github.com/Homebrew/linuxbrew.git
  - PATH=$PWD/linuxbrew/bin:$PATH
  - brew update
  - brew tap homebrew/science
  - brew install -v mumps

